// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8e4821bfDecodeGithubComUjweghShortenerInternalAppHandlers(in *jlexer.Lexer, out *ShortenResponseDto) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8e4821bfEncodeGithubComUjweghShortenerInternalAppHandlers(out *jwriter.Writer, in ShortenResponseDto) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenResponseDto) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8e4821bfEncodeGithubComUjweghShortenerInternalAppHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenResponseDto) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8e4821bfEncodeGithubComUjweghShortenerInternalAppHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenResponseDto) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8e4821bfDecodeGithubComUjweghShortenerInternalAppHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenResponseDto) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8e4821bfDecodeGithubComUjweghShortenerInternalAppHandlers(l, v)
}
func easyjson8e4821bfDecodeGithubComUjweghShortenerInternalAppHandlers1(in *jlexer.Lexer, out *ShortenRequestDto) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8e4821bfEncodeGithubComUjweghShortenerInternalAppHandlers1(out *jwriter.Writer, in ShortenRequestDto) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenRequestDto) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8e4821bfEncodeGithubComUjweghShortenerInternalAppHandlers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenRequestDto) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8e4821bfEncodeGithubComUjweghShortenerInternalAppHandlers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenRequestDto) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8e4821bfDecodeGithubComUjweghShortenerInternalAppHandlers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenRequestDto) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8e4821bfDecodeGithubComUjweghShortenerInternalAppHandlers1(l, v)
}
